asdf

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -68,6 +68,10 @@ jobs:
         with:
           terraform_wrapper: false
 
+      - name: Import Resource Group (if exists)
+        run: |
+          terraform -chdir=global import azurerm_resource_group.rg /subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP_NAME }} || echo "Resource group already imported or not required."
+
       # Step 1: Global Infrastructure Deployment
       - name: Terraform Init for Global
         run: terraform -chdir=global init -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ env.STORAGE_ACCOUNT_CONTAINER }}" -backend-config="key=${{ github.ref_name }}.terraform.tfstate" -backend-config="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" -backend-config="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}"
